---
repos:
  # Check commit messages on commit
  - repo: https://github.com/commitizen-tools/commitizen
    # Specify tag
    rev: v2.29.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
      - id: black-jupyter
        language_version: python3
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^src/
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
# -   id: mixed-line-ending
#     name: mixed line ending
#     description: replaces or checks mixed line ending.
#     entry: mixed-line-ending
#     language: python
#     types: [text]

